theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1 : "undo,redo,separator,bold,italic,underline,separator,bullist,numlist,separator,link,unlink,anchor,image,separator,code"
theme_advanced_buttons2 : ""
theme_advanced_buttons3 : ""
